frame_fusion/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin-app/', include('admin_app.urls')),
    path('admin/', admin.site.urls),
    path('', include('user_app.urls')),
    

]

user_app/urls.py
from django.contrib import admin
from django.urls import path
from  .views import user_view,auth_view

urlpatterns = [
    path('', user_view.index_page ,name='index_page'),
    
    
    # auth endpoints
    path('auth/register/', auth_view.registration_page ,name='registration_page'),
     # user account activation from email
    path('auth/activate/<uidb64>/<token>/', auth_view.activate_user, name='activate_user'),
    # forgot-password
    path('auth/forgot-password/', auth_view.forgot_password_page ,name='forgot_password_page'),
     # login
    path('auth/login/', auth_view.login_page ,name='login_page'),
    # logout
    path('auth/logout/', auth_view.logout_page ,name='logout_page'),
   
    
       # user account reset from email
    path('auth/reset/<uidb64>/<token>/', auth_view.password_reset_confirm, name='password_reset_confirm'),
    

    # genres 
    path('genres/<slug:genre_slug>/', user_view.genres_page, name='genres_page'),
    path('user-genres-list/<slug:slug>/', user_view.user_genres_list, name='user_genres_list'),
    
    # categories
    path('categories/<slug:category_slug>/', user_view.categories_page, name='categories_page'),
    path('user-categories-list/<slug:slug>/', user_view.user_categories_list, name='user_categories_list'),
    
  
    
    # Show
    
    # this is the endpoint that displays the modal popup for show details
      path('shows/<slug:show_slug>/', user_view.show_page, name='show_page'),
      
      # responsible for taking client the the actual video page
    path('show/<slug:show_slug>/watch/<slug:video_slug>/', user_view.video_page, name='video_page'),

    

     
]

admin_app/models.py
from django.db import models

from  django.contrib.auth.models import AbstractUser
from django.utils.text import slugify

class User(AbstractUser):
    # pass
    email = models.EmailField(unique=True, null=True)
    name = models.CharField(max_length=255,null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    brand_name = models.CharField(max_length=255, unique=False, null=True)
    brand_image_url = models.URLField(max_length=255, blank=True, null=True)
   
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS=[]
    #overriding the username_field to take email instead of username and making the required_fields empty 
      

        
class Genre(models.Model):
    class Meta:
          ordering=['-updated_at','created_at']
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
     ]
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='inactive')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)  
        self.name=self.name.capitalize()
        super(Genre, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    


class Category(models.Model):
    class Meta:
          ordering=['-updated_at','created_at']
        #   all currently updated records should come first or default-behaviour, order it in ascending order by the ones currently created
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
     ]
    name = models.CharField(max_length=100,unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='inactive')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)  
        self.name=self.name.capitalize()
        
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name



class Show(models.Model):
    class Meta:
        ordering=['-updated_at','created_at']
    STATUS_CHOICES = [
    ('active', 'Active'),
    ('inactive', 'Inactive'),
    ]
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='inactive')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cover_image_url = models.URLField(max_length=200, blank=True, null=True)
    view_count = models.IntegerField(default=0)
    categories = models.ManyToManyField(Category, related_name='categories_set')
    genres = models.ManyToManyField(Genre, related_name='genres_set')
    

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.title=self.title.capitalize()
        
        super(Show, self).save(*args, **kwargs)

    def __str__(self):
        return self.title




class Video(models.Model):
    # class Meta:
        #   ordering=['-updated_at','created_at']
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
     ]
    title = models.CharField(max_length=255,unique=True,blank=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='inactive')
    thumb_image_url = models.URLField(max_length=255, blank=True, null=True)
    video_url = models.URLField(max_length=255, blank=True, null=True)
    show = models.ForeignKey(Show, on_delete=models.CASCADE, default=None)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    view_count = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)  
        self.title=self.title.capitalize()
        
        super(Video, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    

user_app/models.py
from django.db import models

# Create your models here.

user_app/controllers/auth_view.py
from django.http import HttpResponse
from admin_app.models import Category,Genre,User
from django.shortcuts import render,redirect,get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Count
from admin_app.Forms.config_platform.Forms import UserForm
from user_app.Forms.auth.Forms import LoginForm,ResetPasswordForm,ConfirmResetPasswordForm
from django.contrib.sites.shortcuts import get_current_site
from admin_app.services import Mailer,AppConfig
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.http import HttpRequest
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.utils.http import urlsafe_base64_decode
from django.http import HttpResponse
from django.urls import reverse
from django.http import JsonResponse,HttpResponse
from django.contrib.auth import authenticate,login,logout
from custom_decorators.user.decorators import redirect_authenticated
 
 
@redirect_authenticated
def registration_page(request):
   
   request.session['page'] = 'Registration'
  
   user_with_brand = AppConfig.Ownership.get_owner()
   
   site_name = user_with_brand.brand_name if user_with_brand else None
   site_logo = user_with_brand.brand_image_url if user_with_brand else None
   genres = Genre.objects.filter(status='active').annotate(genre_count=Count('genres_set')).filter(genre_count__gt=0).order_by('-created_at')[:5]
   categories = Category.objects.filter(status='active').annotate(show_count=Count('categories_set')).filter(show_count__gt=0).order_by('-created_at')[:5]
   password=None
   confirm_password=None
   
   if request.method == 'POST':
      
      
      current_site = get_current_site(request)
      
      changed_data=request.POST.copy()
      if changed_data['password']:
         password=changed_data['password']
      if changed_data['confirm_password']:
         confirm_password=changed_data['confirm_password']
      changed_data['brand_name']="_"
      changed_data["brand_image_url"]=current_site
      form = UserForm(data=changed_data)
    

      
      if form.is_valid():
         
         user=form.save(commit=False)
         
         user.set_password(form.cleaned_data['password'])
         user.username=user.name 
         user.is_active=False
         
         
         user.save()
         # send welcome email
         mailer=Mailer.Mailer()
         mailer.send_welcome_email(user)
         mailer.send_email_confirmation(request,user,'user_app/emails/confirmation.html')
         response = JsonResponse({'success': True})
         to_indexpage=reverse('index_page') + '?created=true'
         response['HX-Redirect'] =to_indexpage
         return response
         
       
         
         
      
      context={'site_name':site_name,'site_logo':site_logo,'categories':categories,'genres':genres,'form':form,'password':password,'confirm_password':confirm_password}
      
      # print(form.errors.items())
      return render(request,'user_app/partials/form_elements/user/registration_form.html',context)
      
      
      
   form = UserForm()
   
   context={'site_name':site_name,'site_logo':site_logo,'categories':categories,'genres':genres,'form':form}
   
   return render(request,'user_app/pages/user/registration.html',context)
   
   
 
def activate_user(request: HttpRequest, uidb64: str, token: str) -> HttpResponse:
    # Your logic for activating the user
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, User.DoesNotExist):
        user = None
        return HttpResponse("Something aint ok.")
        


    if user is not None and token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        response = JsonResponse({'success': True})
        to_indexpage=reverse('index_page') + '?activated=true'
        return redirect(to_indexpage)
     
    else:
      to_indexpage=reverse('index_page') + '?activated=false'
      return redirect(to_indexpage)


def password_reset_confirm(request: HttpRequest, uidb64: str, token: str) -> HttpResponse:
   request.session['page'] = 'Forgot Password'
   user_with_brand = AppConfig.Ownership.get_owner()
   
   site_name = user_with_brand.brand_name if user_with_brand else None
   site_logo = user_with_brand.brand_image_url if user_with_brand else None
   genres = Genre.objects.filter(status='active').annotate(genre_count=Count('genres_set')).filter(genre_count__gt=0).order_by('-created_at')[:5]
   categories = Category.objects.filter(status='active').annotate(show_count=Count('categories_set')).filter(show_count__gt=0).order_by('-created_at')[:5]
   
    # Your logic for activating the user
   try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
   except (TypeError, ValueError, User.DoesNotExist):
        user = None
        return HttpResponse("Something aint ok.")
        


   if user is not None and token_generator.check_token(user, token):
      # validate user identity and token
            if request.method == 'POST':
               # handle post request after validation if user sends a post req.
               changed_data=request.POST.copy()
               form=ConfirmResetPasswordForm(data=changed_data)
               if form.is_valid():
                  user.set_password(form.cleaned_data['password'])
                  user.save()
                  # relog user in to prevent losing session
                  login(request,user)
                  
                  response = JsonResponse({'success': True})
                  to_indexpage=reverse('index_page') + '?updated=true'
                  response['HX-Redirect'] =to_indexpage
                  return response
               
                  
                  
               # valid token and user  but validation failed
               
               context={'site_name':site_name,'site_logo':site_logo,'categories':categories,'genres':genres,'form':form}
               return render(request,'user_app/partials/form_elements/user/update_password_form.html',context)
               
         
            # valid token and user 
            form=ConfirmResetPasswordForm()
            context={'site_name':site_name,'site_logo':site_logo,'categories':categories,'genres':genres,'form':form}
            return render(request,'user_app/pages/user/update_password.html',context)
       
   else:
      to_indexpage=reverse('index_page') + '?activated=false'
      return redirect(to_indexpage)

@redirect_authenticated
def forgot_password_page(request):
   request.session['page'] = 'Forgot Password'
  
   user_with_brand = AppConfig.Ownership.get_owner()
   
   site_name = user_with_brand.brand_name if user_with_brand else None
   site_logo = user_with_brand.brand_image_url if user_with_brand else None
   genres = Genre.objects.filter(status='active').annotate(genre_count=Count('genres_set')).filter(genre_count__gt=0).order_by('-created_at')[:5]
   categories = Category.objects.filter(status='active').annotate(show_count=Count('categories_set')).filter(show_count__gt=0).order_by('-created_at')[:5]
   
   if request.method == 'POST':
      changed_data=request.POST.copy()
      form = ResetPasswordForm(data=changed_data)
      
      if form.is_valid():
         form_email=form.cleaned_data.get('email')
         # send reset email
         mailer=Mailer.Mailer()
         user=User.objects.filter(email=form_email).first()
         mailer.send_forgot_password_email(request,user,'user_app/emails/reset_password.html')
         response = JsonResponse({'success': True})
         to_indexpage=reverse('index_page') + '?reset=true'
         response['HX-Redirect'] =to_indexpage
         return response
         
            # form.add_error('password','Wrong Credentials Provided!')
      context={'site_name':site_name,'site_logo':site_logo,'categories':categories,'genres':genres,'form':form}
      
      return render(request,'user_app/partials/form_elements/user/forgot_password_form.html',context)
         
   
   form = ResetPasswordForm()
   


   context={'site_name':site_name,'site_logo':site_logo,'categories':categories,'genres':genres,'form':form}

   return render(request,'user_app/pages/user/forgot_password.html',context)


   
   
@redirect_authenticated
def login_page(request):
   request.session['page'] = 'Login'
  
   user_with_brand = AppConfig.Ownership.get_owner()
   
   site_name = user_with_brand.brand_name if user_with_brand else None
   site_logo = user_with_brand.brand_image_url if user_with_brand else None
   genres = Genre.objects.filter(status='active').annotate(genre_count=Count('genres_set')).filter(genre_count__gt=0).order_by('-created_at')[:5]
   categories = Category.objects.filter(status='active').annotate(show_count=Count('categories_set')).filter(show_count__gt=0).order_by('-created_at')[:5]
   password=None
   
   if request.method == 'POST':
      
      
      
      changed_data=request.POST.copy()
      if changed_data['password']:
         password=changed_data['password']
      
      form = LoginForm(data=changed_data)
      
      if form.is_valid():
         form_email=form.cleaned_data.get('email')
         form_ppassword=form.cleaned_data.get('password')
         user_auth=authenticate(request,email=form_email,password=form_ppassword)

         if user_auth is not None:
            login(request,user_auth)
            response = JsonResponse({'success': True})
            to_indexpage=reverse('index_page') + '?authenticated=true'
            response['HX-Redirect'] =to_indexpage
            return response
         else:
            form.add_error('password','Wrong Credentials Provided!')
      context={'site_name':site_name,'site_logo':site_logo,'categories':categories,'genres':genres,'form':form,'password':password,}
      

user_app/views.py
from django.shortcuts import render

# Create your views here.

user_app/templates/user_app/pages/user_index.html
{% extends 'user_app/user_main_layout.html' %}


{% load custom_filters %}
{% load humanize %}

{% comment %} 
I added load custom_filters because I wanted to:
  -- Find the number of active videos per each show
  1. I created a folder called 'templatetags' to define my custom filters 
  2. added my __init__.py file so that the folder will be treated as a python module
  3.I created a folder called custom_filters and then defined the function active_count in the file and am using it on line 43 in this file
{% endcomment %}

{% block content %}
{% include 'user_app/partials/hero.html' %}

{% comment %} show modal here {% endcomment %}
{% include 'user_app/partials/show_modal.html' %}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            {%    for genre, shows_data in genre_with_shows.items%}
            <div class="trending__product">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-8">
                        <div class="section-title">
                            <h4> {{genre}}</h4>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <div class="btn__all">
                            <a href="#" class="primary-btn">View All ({{shows_data.shows.count}}) <span class="arrow_right"></span></a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <!-- Repeat this block for each product -->
                {%for show in shows_data.shows%}

                    <div class="col-lg-4 col-md-6 col-sm-6" onclick="openShowModal()" hx-get="{% url 'show_page' show.slug %}" hx-target="#show_modal_body" >
                        <div class="product__item">
                            <div class="product__item__pic set-bg" data-setbg="{{ show.cover_image_url }}" style="background-image: url('{{ show.cover_image_url }}');">

                                <div class="ep">{{ show.video_set|active_count }}/{{ show.video_set.count }}</div>

                                <div class="view"><i class="fa fa-eye"></i> {{show.view_count|intword}}</div>
                            </div>
                            <div class="product__item__text">
                                <ul>
                                    {%for category in show.categories.all%}
                                    <li>{{category}}</li>
                                    {%endfor%}
                                </ul>
                                <h5><a href="anime-details.html">{{show}}</a></h5>
                            </div>
                        </div>
                    </div>
                {%endfor%}

                    <!-- Repeat ends -->

                </div>
            </div>
            {% endfor %}
        </div>

        {% include 'user_app/partials/for_you_section.html' %}

        
        
    </div>
</div>


{% endblock content %}

user_app/templates/user_app/pages/video-detail.html
{% extends 'user_app/user_main_layout.html' %} 
{% load static %}
 {% block content %}

 {% comment %} share modal {% endcomment %}
<!-- Button to trigger the modal -->


<!-- Modal -->
<div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title text-white" id="shareModalLabel">Share Video</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <div class="mb-3">
                  <label for="videoUrlInput" class="form-label text-white">Video URL</label>
                  <input type="text"  class="form-control" id="videoUrlInput" value="https://www.example.com/video" readonly>
                  <p id="copySuccessMessage" class="text-success d-none">Video URL copied successfully, you can now share it anywhere possible.</p>
              </div>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-primary" id="copyButton">Copy Link</button>
          </div>
          <div class="modal-footer">
            <div class="btn-group" role="group">
              <a href="#" class="btn btn-primary" id="twitterShare"><i class="fab fa-twitter"></i> Tweet About This!</a>
             
          </div>
          
          </div>
      </div>
  </div>
</div>




<div class="breadcrumb-option">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb__links">
          <a href="/"><i class="fa fa-home"></i> Home</a>
          <a href="#">Show</a>
          <span>{{page_title}}</span>
        </div>
      </div>
    </div>
  </div>
</div>

{% comment %} detail start {% endcomment %}
<section class="anime-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
         
               




                <div class="video-container">
                  <video  src="{{video.video_url}}"  id="player" width="640" height="360" controls poster="{{ video.thumb_image_url }}"></video>
                 

                  {% if current_index > 0 %}
                  <button id="prevButton" class="control-button"><i class="fas fa-backward"></i></button>
              {% endif %}
              {% if current_index < last_video_index %}
                  <button id="nextButton" class="control-button"><i class="fas fa-forward"></i></button>
              {% endif %}



                  <button id="share" class="btn btn-lg mt-3 mb-3" data-bs-toggle="modal" data-bs-target="#shareModal"><i class="fas fa-share" style="color:white"></i></button>
                
              </div>
              

                <div class="anime__details__episodes">
                    <div class="section-title">
                        <h5>PART/EP(ES.)</h5>
                    </div>
                   
                    {% for video_item in show.video_set.all %}
                    {% if video_item.status == 'active' %}
                        <a class="mb-5 {% if video_item == video %}bg-warning{% endif %} video_link" href="{% url 'video_page' show.slug video_item.slug %}">{{ video_item }}</a>
                    {% endif %}
                {% endfor %}
                

                    
                </div>
            </div>
        </div>
   
    </div>
</section>

<style>
  .video-container {
      position: relative;
      display: inline-block;
  }

  .control-button {
      position: absolute;
      top:50%;
      transform: translateY(-50%);
      background-color: rgba(0, 0, 0, 0.5);
      border: none;
      color: white;
      padding: 10px;
      cursor: pointer;
      z-index: 2;
  }

  #prevButton {
      left: 10px;
  }

  #nextButton {
      right: 10px;
  }

  .control-button i {
      font-size: 24px;
  }


  
</style>

<script>
  document.addEventListener('DOMContentLoaded', () => {
      const videoPlayer = document.getElementById('player');
      const links = document.querySelectorAll('.video_link');

      // Extract video details from the show object's video_set.all attribute
      const videos = [
          {% for video in show.video_set.all %}
          {
              url: "{{ video.video_url }}",
              slug: "{{ video.slug }}",
              title: "{{ video.title }}"
          },
          {% endfor %}
      ];

      // Get the index of the current video
      const currentVideoUrl = "{{ video.video_url }}";
      const currentVideoIndex = videos.findIndex(video => video.url === currentVideoUrl);
      let currentIndex = currentVideoIndex !== -1 ? currentVideoIndex : 0;

      // Function to load video by index
      const loadVideo = (index) => {

          const showSlug = '{{ show.slug }}';
          const videoSlug = videos[index].slug;
          const newURL = `/show/${showSlug}/watch/${videoSlug}/`;


          // Update the URL without reloading the page
        //  history.replaceState(null, '', newURL);

          // Highlight the current video link and remove the highlight from others
          links.forEach(link => {
              if (link.innerText === videos[index].title) {
                  link.classList.add('bg-warning');
              } else {
                  link.classList.remove('bg-warning');
              }
          });

         if (videoPlayer) {
            window.location.href=newURL
          
         }

      };



 
      // Add event listeners for next and prev buttons
      const nextButton = document.getElementById('nextButton');
      const prevButton = document.getElementById('prevButton');

      if(nextButton){
        nextButton.addEventListener('click', () => {
            if (currentIndex < videos.length - 1) {
                currentIndex++;
                loadVideo(currentIndex);
            }
        });

      }

     

      if(prevButton){ 
        document.getElementById('prevButton').addEventListener('click', () => {
          if (currentIndex > 0) {
              currentIndex--;
              loadVideo(currentIndex);
          }
      });
    }

      // Add event listener for share button to show the modal
      document.getElementById('share').addEventListener('click', () => {
          $('#shareModal').modal('show');
          const videoUrlInput = document.getElementById('videoUrlInput');
          videoUrlInput.value = window.location.href;
      });

      // Copy button functionality
      document.getElementById('copyButton').addEventListener('click', () => {
          const videoUrlInput = document.getElementById('videoUrlInput');
          videoUrlInput.select();
          document.execCommand('copy');
          const copySuccessMessage = document.getElementById('copySuccessMessage');
          copySuccessMessage.classList.remove('d-none');
          setTimeout(() => {
              copySuccessMessage.classList.add('d-none');
          }, 3000);
      });

      // Function to update share links
      const tweetLink = () => {
          const currentUrl = window.location.href;
          const tweetText = `New Video Uploaded!\n\nTitle: ${videos[currentIndex].title}\n\n`;
          
          const twitterUrl = `https://x.com/intent/tweet?url=${encodeURIComponent(currentUrl)}&text=${encodeURIComponent(tweetText)}`;
          document.getElementById('twitterShare').href = twitterUrl;
          document.getElementById('twitterShare').target = "_blank";

        
      };

     

  
      tweetLink();
  });



  
</script>


{% endblock content %}